<a href="https://colab.research.google.com/github/AvinaashAnandK/DeepLearningJourney/blob/main/DeepML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Index**

| ID | Title | Difficulty | Category | Status |
|----|-------|------------|----------|---------|
| 1 | Matrix times Vector | **easy** | Linear Algebra | Solved |
| 2 | Transpose of a Matrix | **easy** | Linear Algebra | Solved |
| 3 | Reshape Matrix | **easy** | Linear Algebra | Solved |
| 4 | Calculate Mean by Row or Column | **easy** | Linear Algebra | Solved |
| 5 | Scalar Multiplication of a Matrix | **easy** | Linear Algebra | Solved |
| 6 | Calculate Eigenvalues of a Matrix | **medium** | Linear Algebra | Unsolved |
| 7 | Matrix Transformation | **medium** | Linear Algebra | Unsolved |
| 8 | Calculate 2x2 Matrix Inverse | **medium** | Linear Algebra | Unsolved |
| 9 | Matrix times Matrix | **medium** | Linear Algebra | Unsolved |
| 10 | Singular Value Decomposition (SVD) | **hard** | Linear Algebra | Unsolved |
| 11 | Solve Linear Equations using Jacobi Method | **medium** | Linear Algebra | Unsolved |
| 12 | Singular Value Decomposition (SVD) | **hard** | Linear Algebra | Unsolved |
| 13 | Determinant of a 4x4 Matrix using Laplace's Expansion (hard) | **hard** | Linear Algebra | Unsolved |
| 14 | Linear Regression Using Normal Equation | **easy** | Machine Learning | Unsolved |
| 15 | Linear Regression Using Gradient Descent | **easy** | Machine Learning | Unsolved |

# Question 1: Matrix times Vector

---

#### Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

```
Example:
Input:
a = [[1,2],[2,4]], b = [1,2]
Output:
[5, 10]
Reasoning:
1*1 + 2*2 = 5; 1*2+ 2*4 = 10
```

In [12]:
def matrix_dot_vector(a:list[list[int|float]],b:list[int|float])-> list[int|float]:
  rows = len(a)
  cols = len(a[0])
  vector = len(b)

  if cols != vector:
    return -1

  c = []

  for i in range(rows):
    prod = 0
    for j in range(cols):
      prod += a[i][j] * b [j]
    c.append(prod)

  return c

In [13]:
a = [[1,2],[2,4]]; b = [1,2]

In [14]:
matrix_dot_vector(a,b)

[5, 10]

# Question 2: Transpose of a Matrix

---

#### Write a Python function that computes the transpose of a given matrix.

Example:
```
Input:
a = [[1,2,3],[4,5,6]]
Output:
[[1,4],[2,5],[3,6]]
Reasoning:
The transpose of a matrix is obtained by flipping rows and columns.
```


In [15]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	mat = []
	rows = len(a)
	cols = len(a[0])
	for j in range(cols):
		temp = []
		for i in range(rows):
			temp.append(a[i][j])
		mat.append(temp)
	return mat

# Question 3: Write a Python function that reshapes a given matrix into a specified shape.

---

```
Example:
Input:
a = [[1,2,3,4],[5,6,7,8]], new_shape = (4, 2)
Output:
[[1, 2], [3, 4], [5, 6], [7, 8]]
Reasoning:
The given matrix is reshaped from 2x4 to 4x2.
```

In [6]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	mat = []
	rows = len(a)
	cols = len(a[0])

	for row in a:
		mat.extend(row)

	reshaped_matrix = []

	for i in range(0,new_shape[0]*new_shape[1],new_shape[1]):
		reshaped_matrix.append(mat[i:i+new_shape[1]])

	return reshaped_matrix

In [ ]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	mat = np.array(a)
	reshaped_matrix = mat.reshape(new_shape)

	return reshaped_matrix

# Question 4: Calculate Mean by Row or Column

---
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

```
Example:
Input:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], mode = 'column'
Output:
[4.0, 5.0, 6.0]
Reasoning:
Calculating the mean of each column results in [(1+4+7)/3, (2+5+8)/3, (3+6+9)/3].
```

In [ ]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
  means = []
  if mode == 'row':
    for row in matrix:
      means.append(sum(row) / len(row))
  elif mode == 'column':
    for i in range(len(matrix[0])):
      col = [row[i] for row in matrix]
      means.append(sum(col)/len(col))
  return means

# Question 5: Scalar Multiplication of a Matrix

---
Write a Python function that multiplies a matrix by a scalar and returns the result.

```
Example:
Input:
matrix = [[1, 2], [3, 4]], scalar = 2
Output:
[[2, 4], [6, 8]]
Reasoning:
Each element of the matrix is multiplied by the scalar.
```

In [7]:
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return [[scalar * item for item in row] for row in matrix]

# Question 6: Calculate Eigenvalues of a Matrix

---

Write a Python function that calculates the eigenvalues of a 2x2 matrix. The function should return a list containing the eigenvalues, sort values from highest to lowest.

```
Example:
Input:
matrix = [[2, 1], [1, 2]]
Output:
[3.0, 1.0]
```

# Question 11: Solve Linear Equations using Jacobi Method

---

Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

```
Example:
Input:
A = [[5, -2, 3], [-3, 9, 1], [2, -1, -7]], b = [-1, 2, 3], n=2
Output:
[0.146, 0.2032, -0.5175]
Reasoning:
The Jacobi method iteratively solves each equation for x[i] using the formula x[i] = (1/a_ii) * (b[i] - sum(a_ij * x[j] for j != i)), where a_ii is the diagonal element of A and a_ij are the off-diagonal elements.
```

In [18]:
import numpy as np
def solve_jacobi(A: np.ndarray, b: np.ndarray, n: int) -> list:
  x = np.zeros(len(A))
  x_temp = np.zeros(len(A))

  for step in range(n):
    for i,x_old in enumerate(x):
      x_new = (b[i] - np.sum([A[i][j]*x[j] for j in range(len(x)) if j != i]))/ A[i][i]
      x_temp[i] = x_new

    x = x_temp.copy()

  return np.round(x,4).tolist()

# Question 12: Singular Value Decomposition

---

Write a Python function that approximates the Singular Value Decomposition on a 2x2 matrix. Return the result the results as a tuple with U, sigma and V.

```
Example:
Input:
a = [[2, 1], [1, 2]]
Output:
(array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))
Reasoning:
U is the first matrix, sigma is the second vector, and V is the third matrix.
```

In [1]:
a = [[2, 1], [1, 2]]

In [16]:
#Straight forward implementation using numpy
import numpy as np
def svd_2x2_singular_values(A: np.ndarray) -> tuple:
  U,s,vt =np.linalg.svd(A, full_matrices=False)
  v = vt.T
  return (U,s,v)

In [18]:
#Considering all elements
import numpy as np
def svd_2x2_singular_values(A: np.ndarray) -> tuple:
  a = A
  b = a.T @ a
  iterations = 1
  # error = 1e-7
  v = np.eye(len(A))
  for iter in range(iterations):
      #Calculate the rotation angle
      theta = 0.5 * np.arctan2(2*b[0,1],b[0,0]-b[1,1])

      #Calculate the rotation matrix
      r = np.array(
          [
              [np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]
          ]
      )

      b = r.T @ b @ r

      v = v @ r

  s = np.sqrt(np.diag(b))
  idx = np.argsort(s)[::-1]

  s = s[idx]
  v = v[:, idx]

  U = a @ v / s

  return (U,s,v.T)

# Question 13: Determinant of a 4x4 Matrix using Laplace's Expansion (hard)


---

Write a Python function that calculates the determinant of a 4x4 matrix using Laplace's Expansion method. The function should take a single argument, a 4x4 matrix represented as a list of lists, and return the determinant of the matrix. The elements of the matrix can be integers or floating-point numbers. Implement the function recursively to handle the computation of determinants for the 3x3 minor matrices.

```
Example:
Input:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
Output:
0

```
Reasoning:
Using Laplace's Expansion, the determinant of a 4x4 matrix is calculated by expanding it into minors and cofactors along any row or column. Given the symmetrical and linear nature of this specific matrix, its determinant is 0. The calculation for a generic 4x4 matrix involves more complex steps, breaking it down into the determinants of 3x3 matrices.

In [38]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [39]:
import numpy as np

def determinant_4x4(matrix: list[list[int|float]]) -> float:
  matrix = np.array(matrix)
  n = matrix.shape[0]

  if n <= 2:
    return (-matrix[0,1]*matrix[1,0]) + (matrix[0,0]*matrix[1,1])
  else:
    det = 0
    for i in range(n):
      sliced_matrix = matrix[np.array(list(range(1)) + list(range(1+1, matrix.shape[0])))[:, np.newaxis], np.array(list(range(i)) + list(range(i+1, matrix.shape[1])))]
      det += (-1)**(i) * matrix[1,i] * determinant_4x4(sliced_matrix)

  return det

In [40]:
determinant_4x4(a)

0

# Question 14: Linear Regression Using Normal Equation


---

Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

```
Example:
Input:
X = [[1, 1], [1, 2], [1, 3]], y = [1, 2, 3]
Output:
[0.0, 1.0]

```

In [3]:
X = [[1, 1], [1, 2], [1, 3]]; y = [1, 2, 3]

In [2]:
import numpy as np
def linear_regression_normal_equation(X: list[list[float]], y: list[float]) -> list[float]:
	x = np.array(X)
	y = np.array(y)
	y = y.reshape(-1,1)
	theta = np.round(np.linalg.inv(x.T @ x) @ x.T @ y,4).flatten().tolist()
	return theta

# Question 15: Linear Regression Using Gradient Descent

---

Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.


```
Input:
X = np.array([[1, 1], [1, 2], [1, 3]]), y = np.array([1, 2, 3]), alpha = 0.01, iterations = 1000
Output:
np.array([0.1107, 0.9513])
Reasoning:
The linear model is y = 0.0 + 1.0*x, which fits the input data after gradient descent optimization.
```

# Question 16: Feature Scaling Implementation

---

Write a Python function that performs feature scaling on a dataset using both standardization and min-max normalization. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. It should return two 2D NumPy arrays: one scaled by standardization and one by min-max normalization. Make sure all results are rounded to the nearest 4th decimal.


```
Input:
data = np.array([[1, 2], [3, 4], [5, 6]])
Output:
([[-1.2247, -1.2247], [0.0, 0.0], [1.2247, 1.2247]], [[0.0, 0.0], [0.5, 0.5], [1.0, 1.0]])
Reasoning:
Standardization rescales the feature to have a mean of 0 and a standard deviation of 1. Min-max normalization rescales the feature to a range of [0, 1], where the minimum feature value maps to 0 and the maximum to 1.
```

# Question 16: K-Means Clustering

---

Your task is to write a Python function that implements the k-Means clustering algorithm. This function should take specific inputs and produce a list of final centroids. k-Means clustering is a method used to partition n points into k clusters. The goal is to group similar points together and represent each group by its center (called the centroid).

Function Inputs:
points: A list of points, where each point is a tuple of coordinates (e.g., (x, y) for 2D points)
k: An integer representing the number of clusters to form
initial_centroids: A list of initial centroid points, each a tuple of coordinates
max_iterations: An integer representing the maximum number of iterations to perform
Function Output:
A list of the final centroids of the clusters, where each centroid is rounded to the nearest fourth decimal.

```
Input:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)], k = 2, initial_centroids = [(1, 1), (10, 1)], max_iterations = 10
Output:
[(1, 2), (10, 2)]
Reasoning:
Given the initial centroids and a maximum of 10 iterations, the points are clustered around these points, and the centroids are updated to the mean of the assigned points, resulting in the final centroids which approximate the means of the two clusters. The exact number of iterations needed may vary, but the process will stop after 10 iterations at most.
```

